# Generated by Django 3.2 on 2021-05-31 10:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=64)),
                ('type', models.IntegerField(choices=[(1, 'Активный'), (0, 'Изменчивый'), (-1, 'Пассивный')], default=1)),
            ],
            options={
                'verbose_name': 'Бухгалтерский счет',
                'verbose_name_plural': 'План счетов',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('type', models.IntegerField(choices=[(1, 'Увеличение'), (0, 'Перетекание'), (-1, 'Уменьшение')], default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.CharField(max_length=256)),
                ('status', models.IntegerField(choices=[(1, 'Включена'), (0, 'Выключена')], default=1)),
                ('account_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.ledgeraccount')),
                ('account_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.ledgeraccount')),
            ],
            options={
                'verbose_name': 'Бухгалтерская проводка',
                'verbose_name_plural': 'Бухгалтерские проводки',
            },
        ),
    ]
