# Generated by Django 3.2 on 2021-04-29 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0005_auto_20210427_1254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="entry",
            name="updates_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
