# Generated by Django 3.2 on 2021-05-31 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('task', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('status', models.IntegerField(choices=[(1, 'Делается'), (0, 'Сделано')], default=1)),
                ('comment', models.CharField(max_length=256)),
                ('creator', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
