# Generated by Django 3.2 on 2021-06-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoentry',
            name='date',
        ),
        migrations.AddField(
            model_name='todoentry',
            name='date_range',
            field=models.CharField(default='', max_length=64),
        ),
    ]
