name: Publish
on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "CI pipeline name"
        required: false
        default: "run_tests.yml"

jobs:
  echo:
    runs-on: ubuntu-latest
    environment:
      name: foo
      url: www.google.com
    steps:
      - name: Echo message
        run: echo '${{ github.event.inputs.run_tests }}'